[package]
name = "color-flood-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.0.32", features = ["derive"] }
owo-colors = "3.5.0"
z3 = "0.11.2"
